headstart_size: 365
name: anomaly_transformer    # Transformer AE
hparams:
  input_dim: 193
  hidden_dim: 64
  nhead: 4
  num_layers: 2
  seq_len: 14
  learning_rate: 0.001
  batch_size: 64
  train_ratio: 0.7
  val_ratio: 0.1
sequence_method: sliding_window

trainer:
  max_epochs: 10
